-- UTILIZANDO O IS TRUE E IS NOT TRUE
--PRIMEIRO EXEMPLO RETORNANDO TUDO NA TABELA ONDE O DOMESTIC E VERDADEIRO (O CAMPO PRECISA SER BOOLEANO, OU SEJA, VERDADEIRO OU FALSO) (TAMBEM LIMITEI A 1OO LINHAS)
select * from `bigquery-public-data.chicago_crime.crime`
where domestic is true
LIMIT 100;



--SEGUNDO EXEMPLO RETORNANDO TUDO NA TABELA ONDE O DOMESTIC E FALSO (O CAMPO PRECISA SER BOOLEANO, OU SEJA, VERDADEIRO OU FALSO) (TAMBEM LIMITEI A 1OO LINHAS)
select * from `bigquery-public-data.chicago_crime.crime`
where domestic is not true
LIMIT 100;
