--CODIGO PARA VALOR CONTAR UNICO REALIZANDO INNER JOIN (OU SEJA, PEGANDO INFORMAÇÕES DE DUAS TABELAS) 


SELECT COUNT(DISTINCT CODIGO) AS total_valores_unicos
FROM EMX_INCIDENTES i
INNER JOIN EMX_RESPOSTAS_INCIDENTE ri  ON i.emx_incidentes_id = ri.emx_incidentes_id
