--SOBRE O LIMIT - LIMITAR A QUANTIDADE
--buscando toda a tabela actor
--o LIMIT LISTA 10 ACTOR_ID A PARTIR DO NUMERO CINCO
--PRIMEIRO COLOCO A PARTIR DE QUAL NUMERO E DEPOIS EU COLOCO A QUANTIDADE QUE PRECISO

select * from actor
LIMIT 4, 10
